### ISSUE TITLE
name is already used by an existing object

### ISSUE THREAD

**Issue by binayak87** [mbleron/oracle#10]
ORA-00955: name is already used by an existing object
ORA-06512: at "SYS.EXCELTABLE", line 1412
ORA-06512: at "SYS.EXCELTABLE", line 1464
ORA-06512: at "SYS.EXCELTABLE", line 1572
ORA-06512: at "SYS.EXCELTABLE", line 2034
ORA-06512: at "SYS.EXCELTABLEIMPL", line 60
ORA-06512: at line 1

When I am trying to run a select query I am getting this error

**Comment by binayak87** [comment]
Issues solved Needed to drop table TMP$XLTABLE_SST_30256

**Comment by binayak87** [comment]
ORA-01706: user function result value was too large
ORA-06512: at "SCOTT.EXCELTABLE", line 1414
ORA-06512: at "SCOTT.EXCELTABLE", line 1464
ORA-06512: at "SCOTT.EXCELTABLE", line 1572
ORA-06512: at "SCOTT.EXCELTABLE", line 2034
ORA-06512: at "SCOTT.EXCELTABLEIMPL", line 60
ORA-06512: at line 1


This is a new issue

**Comment by mbleron** [comment]
Please give your full database version (SELECT * FROM v$version), and attach a sample Excel file to reproduce the problem.
Thanks.

**Comment by binayak87** [comment]
I can't share the document sample openly. If there's a way to share the document privately I can share.

**Comment by mbleron** [comment]
You may mail me directly.
Don't forget to state your db version.

**Comment by mbleron** [comment]
Got your email, thanks.
You're on 11.2.0.1, and as stated in the [user guide](https://github.com/mbleron/oracle/blob/master/ExcelTable/README.md), it's not a supported version : 
> ExcelTable requires Oracle Database 11.2.0.2 and onwards.
> 
> Note that the interface may work as well on version 11.1.0.6, 11.1.0.7 and 11.2.0.1, with limited support for CLOB projections, but that scenario has not been tested.
> 

Anyway, I'll see if I can put together a workaround for that version.

**Comment by mbleron** [comment]
Fixed in ExcelTable 1.6.1 for Oracle 11.2.0.1
