### ISSUE TITLE
[Error] Execution (4: 10): ORA-22285: non-existent directory or file for FILEOPEN operation

### ISSUE THREAD

**Issue by Vardhan6y** [mbleron/oracle#3]
Hi Team

I am getting this error while executing the query 

select t.*
from table(
       ExcelTable.getRows(
         ExcelTable.getFile('C:\Oracle','ooxdata3.xlsx')
         , 'DataSource'
         , ' "SRNO"    number
         , "NAME"    varchar2(10)
         , "VAL"     number
         , "DT"      date
         , "SPARE1"  varchar2(6)
         , "SPARE2"  varchar2(6)'
         , 'A2'
       )
     ) t
;
[Error] Execution (4: 10): ORA-22285: non-existent directory or file for FILEOPEN operation
ORA-06512: at "SYS.DBMS_LOB", line 805
ORA-06512: at "APPS.EXCELTABLE", line 1868

Requesting you to please help.

Thanks
Vardhan

**Comment by mbleron** [comment]
Hi,

The first argument of `ExcelTable.getFile` is an Oracle directory object, **not** a file path.
So you first have to create the directory, e.g. : 
`CREATE OR REPLACE DIRECTORY data_dir AS 'C:\Oracle';`
Then you can use 'DATA_DIR' in getFile function. 
Of course, that's assuming the database has actually access to that directory, i.e. it must be somewhere on the database server itself or on a network location accessible by the db. It cannot be a path on your local workstation.

**Comment by mbleron** [comment]
Closing this as "not a issue"
