### ISSUE TITLE
Error while compiling the below sql used in insert statement--PL/SQL: ORA-22905: cannot access rows from a non-nested table item

### ISSUE THREAD

**Issue by Vardhan6y** [mbleron/oracle#5]
create or replace procedure(v_file_name varchar2)
as
begin
insert into xxx
SELECT T.*   
              FROM TABLE (ExcelTable.getRows (
                           ExcelTable.getFile ('DATA_DIR', V_FILE_NAME)
                            ,'Sheet1'
                            ,' "Contract"    varchar2(100)
                              , "BANK_ACCOUNT"    varchar2(100)
                              , "CCID_Cashpool"    varchar2(100)
                              , "LE_CURR"      varchar2(100)
                              , "CURR"   varchar2(5)
                              , "AMT"  number ','A2')  ) T ;

exception
when others then
dbms_output.put_line('In others of proc..');

end;

while compiling the procedure i am getting the following error.
PL/SQL: ORA-22905: cannot access rows from a non-nested table item

Requesting you to please help me on the same.

Thanks
YV

**Comment by MikeKutz** [comment]
Recent discussion on the Oracle Community forum suggest that you need to do this as Dynamic SQL.
https://community.oracle.com/thread/4069109

The answer to that post points to an AskTom thread
https://asktom.oracle.com/pls/apex/f?p=100:11:0::::P11_QUESTION_ID:9536127800346657493

I'd change the `V_FILE_NAME` variable into a BIND variable then use
```sql
EXECUTE IMMEDIATE sql USING v_file_name;
```

I haven't tested it.

MK

**Comment by mbleron** [comment]
Hi,

It's not entirely clear what you're trying to do. 
You mention "insert" yet you post an invalid procedure with a BULK COLLECT operation.

About the actual error, yes it's a known PL/SQL limitation.
As mentioned by Mike, and on my [blog](https://odieweblog.wordpress.com/2016/06/21/reading-an-excel-file-xlsx-as-an-external-table/#comments) as well (see comment by Robert Chalton), the workaround is to use dynamic SQL.

In case you want to use a cursor loop instead, the getCursor() function can be used, saving you the trouble of writing dynamic SQL code. Combined with a BULK COLLECT fetch and FORALL, it can even be as fast as a straightforward INSERT ... SELECT statement, 
e.g.

```
declare

  r  bigfile_table%rowtype;
  type tt is table of bigfile_table%rowtype;
  t  tt;
  c  sys_refcursor;

begin

  ExcelTable.setFetchSize(100);
  
  c := ExcelTable.getCursor(
         p_file   => ExcelTable.getFile('TMP_DIR','bigfile.xlsx')
       , p_sheet  => 'data'
       , p_cols   => q'{ 
            "ID"           number
          , "FIRST_NAME"   varchar2(15)
          , "LAST_NAME"    varchar2(20)
          , "EMAIL"        varchar2(30)
          , "GENDER"       varchar2(10)
          , "IP_ADDRESS"   varchar2(16)
          , "COMMENT"      varchar2(4000)
          , "IMAGE"        varchar2(4000)
          , "DT"           date  format 'DD/MM/YYYY'

         }'
       , p_range  => 'A2'
       , p_method => exceltable.STREAM_READ
       ); 
  
  loop

    fetch c bulk collect into t limit 100;
    exit when t.count = 0;
    
    forall i in 1 .. t.count
    insert into bigfile_table values t(i);
    
  end loop;
       
  close c;

end;
/
```

I'm also currently developing a set of routines dedicated to direct DML operations (INSERT, UPDATE, DELETE) without resorting to the SQL Table interface. Stay tuned.

**Comment by MikeKutz** [comment]
Don't forget MERGE
