### ISSUE TITLE
Getting  ODCITABLESTART callout Error

### ISSUE THREAD

**Issue by Rajeevrachamalla** [mbleron/oracle#6]
Hi Ron,

This is very help full.But when i execute the below i'm getting error like "ORA-29913: error in executing ODCITABLESTART callout" .

There were three columns in the excel and trying to read the same with ExcelTable Package.

![image](https://user-images.githubusercontent.com/32564683/31268032-2f93094e-aa98-11e7-9e20-a8dd1ebfeadf.png)

Query used:
select t.*
   from table(
          ExcelTable.getRows(
            ExcelTable.getFile('FTP_IN','Test.xlsx')
          , 'DataSource'
          , ' "Country_Code"    varchar2(10)
            , "Person Number"    number
            , "Element_Name"     varchar2(50) '
          , 'A2'
          )
        ) t
 ;

**Comment by mbleron** [comment]
I'd need the Excel file to reproduce the issue.
Are you sure the sheet is actually named 'DataSource'?

**Comment by mbleron** [comment]
Closing this issue.
Please reopen if you still have any issue, and provide a sample file.
