### ISSUE TITLE
PLCalc serialize - missing parentheses for certain divide and subtract equations 

### ISSUE THREAD

**Issue by csnider31** [mbleron/oracle#8]
I've been using functions _compile_ and _serialize_ to validate and convert some equations to SQL expressions.  There is an issue where parentheses aren't preserved in some situations.  See below.

Example input: x - (y + z)
Example output: X - Y + Z

Example 2 input: x / (y * z)
Example 2 output: X / Y * Z

For a fix that seems to work, I changed line 1690 from:
`if st(j).prec < oprc or ( st(j).prec <= oprc and asso = 1 ) then`

to:
`if st(j).prec < oprc or ( st(j).prec <= oprc and ( asso = 1 or strval in ('/','-') ) ) then`

There's probably a better solution.  I tried changing the associativity for those operators, but that caused other issues as I expected.  

Thanks for the great package!

**Comment by mbleron** [comment]
Thanks for reporting the issue.
I'll look into this ASAP.

**Comment by mbleron** [comment]
Fixed in version 1.1
I've implemented the same fix you found (using the internal token typecodes instead of the symbols).
